# Generated by Django 3.0.4 on 2020-03-27 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('html', models.TextField(blank=True, null=True, verbose_name='HTML')),
            ],
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_requisitos', to='ayuda.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Tipooperacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('requisitos', models.ManyToManyField(to='ayuda.Requisito')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipousuario', models.IntegerField(default=1)),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=45, verbose_name='Apellidos')),
                ('email', models.CharField(max_length=45, verbose_name='E-Mail')),
                ('telefono', models.CharField(max_length=12, verbose_name='Teléfono')),
                ('coordx', models.CharField(max_length=20, verbose_name='Coordenada X')),
                ('coordy', models.CharField(max_length=20, verbose_name='Coordenada Y')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('dni', models.CharField(max_length=8, verbose_name='Número DNI')),
                ('imgdni', models.FileField(blank=True, default='no-dni.png', null=True, upload_to='', verbose_name='Imagen DNI')),
                ('imgpersona', models.FileField(blank=True, default='no-img.png', null=True, upload_to='', verbose_name='Imagen de persona')),
                ('imghogar', models.FileField(blank=True, default='no-img.png', null=True, upload_to='', verbose_name='Imagen de hogar')),
                ('fecharegistro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['apellido'],
            },
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('imgcomprobante', models.FileField(blank=True, default='no-dni.png', null=True, upload_to='', verbose_name='Imagen comprobante')),
                ('monto', models.IntegerField(blank=True, default=0, verbose_name='Monto ayuda')),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('personas', models.ManyToManyField(to='ayuda.Persona')),
            ],
        ),
    ]
