# Generated by Django 3.0.4 on 2020-03-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayuda', '0002_remove_operacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='estado',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
