# Generated by Django 3.0.4 on 2020-04-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayuda', '0003_operacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipooperacions',
            field=models.ManyToManyField(to='ayuda.Tipooperacion'),
        ),
        migrations.AddField(
            model_name='tipooperacion',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='docTipoOperacion', verbose_name='Documento tipo de operación'),
        ),
        migrations.AddField(
            model_name='tipooperacion',
            name='imagen',
            field=models.ImageField(blank=True, default='no-img-TOP.png', null=True, upload_to='imgTipoOperacion', verbose_name='Imagen tipo de operación'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='imgdni',
            field=models.ImageField(blank=True, default='no-dni.png', null=True, upload_to='', verbose_name='Imagen DNI'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='imghogar',
            field=models.ImageField(blank=True, default='no-img.png', null=True, upload_to='', verbose_name='Imagen de hogar'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='imgpersona',
            field=models.ImageField(blank=True, default='no-img.png', null=True, upload_to='', verbose_name='Imagen de persona'),
        ),
    ]
