# Generated by Django 3.0.4 on 2020-04-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayuda', '0004_auto_20200402_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='nrooperacion',
            field=models.CharField(blank=True, default=0, max_length=20, verbose_name='Nro de operación'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='estado',
            field=models.IntegerField(blank=True, default=True),
        ),
    ]
