# Generated by Django 3.0.4 on 2020-04-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayuda', '0005_auto_20200403_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacion',
            old_name='monto',
            new_name='montoayuda',
        ),
        migrations.AddField(
            model_name='operacion',
            name='montopagado',
            field=models.IntegerField(blank=True, default=0, verbose_name='Monto ayuda'),
        ),
    ]
